---
- hosts: all
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=script.sh dest=/home/vagrant mode=0777

     - name: Execute the script
       command: sh /home/vagrant/script.sh
