---
- name: download wordpress
  get_url: url=https://wordpress.org/{{ wp_version }}.tar.gz dest={{ wp_srcdir }}/wordpress-{{ wp_version }}.tar.gz 
#checksum="{{ wp_shasum }}" 
#  command: /usr/bin/wget -c https://wordpress.org/{{ wp_version }}.tar.gz
#  args: chdir={{ wp_srcdir }} creates={{ wp_srcdir}}/{{ wp_version }}.tar.gz
#  register: wp_download

- name: extract wordpress
  command: chdir="{{ wp_srcdir }}" bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates={{ wp_srcdir }}/wordpress


#  shell: "tar xzf latest.tar.gz && mv wordpress {{ wp_srcdir }}/{{ wp_sitedir }}
#  args: chdir={{ wp_srcdir }} creates={{ wp_srcdir }}/{{ wp_sitedir }}
#  when: wp_download.rc == 0

