---
- name: download wordpress
  get_url: url=https://wordpress.org/{{ wp_version }}.tar.gz dest={{ wp_srcdir }}/wordpress-{{ wp_version }}.tar.gz 

- name: extract wordpress
  command: chdir="{{ wp_srcdir }}" bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates={{ wp_srcdir }}/wordpress


