---
galaxy_info:
  author: Rafal Walas
  description: MySQL Database Role
  company: Private
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
      - all
  - name: Ubuntu
    versions:
      - all
  categories:
  - database: sql

