- name: instsall mysql client
  yum: name="{{ pkg.client }}" state=present update_cache=yes
- name: install mysql server
  yum: name="{{ pkg.server }}" state=present update_cache=yes
  when: server
- name: install python packages
  yum: name="{{ pkg.python }}" state=present update_cache=yes
  

