- name: copy over the configuration file
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644
#  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf mode=0644
  notify: restart nginx
- name: create directory for the static content
  file: path=/etc/nginx/html state=directory
- name: copy over website content
  copy: src=index.html dest=/etc/nginx/html/index.html

